name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release --no-build

    # Add a step to list the contents of the bin/Release directory
    - name: List bin/Release directory
      run: ls -R bin/Release

    # Add a step to find the .nupkg file
    - name: Find .nupkg file
      run: find . -name "*.nupkg"
      
    - name: Publish to GitHub Packages
      run: dotnet nuget push /home/runner/work/Specification/Specification/Specification/bin/Release/SpecificationRepository.1.0.0.nupkg --api-key ${{ secrets.PACKAGE_TOKEN }} --source "https://nuget.pkg.github.com/DarkTroubadour1/index.json"
